using System.Globalization;
using System.Text;
using System.Web;
using D365Xray.Core.Model;

namespace D365Xray.Reporting;

/// <summary>
/// Exports a <see cref="RiskReport"/> as a self-contained HTML document
/// with inline CSS, Chart.js charts, dark mode toggle, deep links,
/// environment inventory, and collapsible finding groups.
/// Produces <c>report.html</c> in the output directory.
/// </summary>
internal sealed class HtmlReportExporter
{
    public async Task ExportAsync(
        RiskReport report,
        string outputDirectory,
        CancellationToken cancellationToken = default)
    {
        Directory.CreateDirectory(outputDirectory);
        var path = Path.Combine(outputDirectory, "report.html");
        var html = Build(report);
        await File.WriteAllTextAsync(path, html, Encoding.UTF8, cancellationToken);
    }

    internal static string Build(RiskReport report)
    {
        var sb = new StringBuilder(16_384);
        sb.AppendLine("<!DOCTYPE html>");
        sb.AppendLine("<html lang=\"en\">");
        sb.AppendLine("<head>");
        sb.AppendLine("<meta charset=\"utf-8\">");
        sb.AppendLine("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
        sb.AppendLine("<title>D365 X-Ray Risk Report</title>");
        sb.AppendLine("<style>");
        AppendCss(sb);
        sb.AppendLine("</style>");
        sb.AppendLine("</head>");
        sb.AppendLine("<body>");

        // Header with dark mode toggle
        sb.AppendLine("<header>");
        sb.AppendLine("<div class=\"header-row\">");
        sb.AppendLine("<div>");
        sb.AppendLine("<h1>D365 X-Ray Risk Report</h1>");
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"<p class=\"meta\">Captured {Encode(report.Metadata.CapturedAtUtc.ToString("u"))} &middot; Tool v{Encode(report.Metadata.ToolVersion)} &middot; <span class=\"mode-badge\">{Encode(report.ComparisonMode.ToString())}</span>{BuildVersionBadge(report)}</p>");
        sb.AppendLine("</div>");
        sb.AppendLine("<button id=\"theme-toggle\" class=\"theme-btn\" title=\"Toggle dark mode\" aria-label=\"Toggle dark mode\">&#9790;</button>");
        sb.AppendLine("</div>");
        sb.AppendLine("</header>");
        sb.AppendLine("<main>");

        // Dashboard row: SVG gauge + KPI cards
        AppendDashboard(sb, report);

        // Executive Summary (auto-generated insights)
        AppendExecutiveSummary(sb, report);

        // Environment inventory
        if (report.EnvironmentSummaries.Count > 0)
        {
            AppendEnvironmentInventory(sb, report);
        }
        else
        {
            AppendEnvironmentsList(sb, report);
        }

        // Solution breakdown (custom vs Microsoft)
        AppendSolutionBreakdown(sb, report);

        // Custom artifact drill-downs
        AppendCustomArtifacts(sb, report);

        // Organization Settings audit
        AppendSettingsAudit(sb, report);

        // Plugin Registration Map
        AppendPluginRegistrationMap(sb, report);

        // Security Posture
        AppendSecurityPosture(sb, report);

        // Environment Variables
        AppendEnvironmentVariables(sb, report);

        // Entity Governance
        AppendEntityGovernance(sb, report);

        // Severity breakdown as bar chart
        AppendSeveritySection(sb, report);

        // Analysis coverage
        AppendAnalysisCoverage(sb, report);

        // Findings
        AppendFindings(sb, report);

        // AI Enrichment
        if (report.AiEnrichment is not null)
        {
            AppendAiSection(sb, report);
        }

        sb.AppendLine("</main>");
        sb.AppendLine("<footer><p>Generated by <strong>d365-xray</strong></p></footer>");

        // Chart.js + inline script
        AppendScripts(sb, report);

        sb.AppendLine("</body>");
        sb.AppendLine("</html>");

        return sb.ToString();
    }

    // ── Dashboard ───────────────────────────────────────────

    private static void AppendDashboard(StringBuilder sb, RiskReport report)
    {
        var score = report.OverallRiskScore;
        var level = report.OverallRiskLevel;
        var levelClass = level.ToString().ToLowerInvariant();
        var angle = score / 100.0 * 180.0;
        // SVG arc for gauge (half circle)
        var rad = angle * Math.PI / 180.0;
        var x = 60 + 50 * Math.Cos(Math.PI - rad);
        var y = 65 - 50 * Math.Sin(Math.PI - rad);
        var largeArc = angle > 90 ? 1 : 0;

        sb.AppendLine("<section class=\"dashboard\">");

        // SVG Gauge
        sb.AppendLine("<div class=\"gauge-card\">");
        sb.AppendLine("<svg viewBox=\"0 0 120 75\" class=\"gauge-svg\">");
        sb.AppendLine("  <path d=\"M 10 65 A 50 50 0 0 1 110 65\" fill=\"none\" stroke=\"var(--gauge-bg)\" stroke-width=\"8\" stroke-linecap=\"round\"/>");
        if (score > 0)
        {
            sb.AppendLine(CultureInfo.InvariantCulture,
                $"  <path d=\"M 10 65 A 50 50 0 {largeArc} 1 {x:F1} {y:F1}\" fill=\"none\" stroke=\"var(--color-{levelClass})\" stroke-width=\"8\" stroke-linecap=\"round\"/>");
        }
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"  <text x=\"60\" y=\"58\" text-anchor=\"middle\" class=\"gauge-score\">{score}</text>");
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"  <text x=\"60\" y=\"72\" text-anchor=\"middle\" class=\"gauge-label\">{level}</text>");
        sb.AppendLine("</svg>");
        sb.AppendLine("</div>");

        // KPI cards
        sb.AppendLine("<div class=\"kpi-grid\">");
        AppendKpiCard(sb, "Findings", report.Findings.Count.ToString(CultureInfo.InvariantCulture), "total");
        var critical = report.SeverityCounts.GetValueOrDefault(Severity.Critical);
        var high = report.SeverityCounts.GetValueOrDefault(Severity.High);
        AppendKpiCard(sb, "Critical", critical.ToString(CultureInfo.InvariantCulture), "critical");
        AppendKpiCard(sb, "High", high.ToString(CultureInfo.InvariantCulture), "high");
        AppendKpiCard(sb, "Environments", report.ComparedEnvironments.Count.ToString(CultureInfo.InvariantCulture), "total");

        // Architect-relevant KPIs
        var customSolCount = report.SolutionInventories.SelectMany(i => i.Solutions).Count(s => !s.IsMicrosoft);
        var unmanagedCount = report.SolutionInventories.SelectMany(i => i.Solutions).Count(s => !s.IsManaged && !s.IsMicrosoft);
        AppendKpiCard(sb, "Custom Solutions", customSolCount.ToString(CultureInfo.InvariantCulture), "total");
        AppendKpiCard(sb, "Unmanaged", unmanagedCount.ToString(CultureInfo.InvariantCulture), unmanagedCount > 0 ? "high" : "total");
        sb.AppendLine("</div>");

        sb.AppendLine("</section>");
    }

    private static void AppendKpiCard(StringBuilder sb, string label, string value, string cssClass)
    {
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"<div class=\"kpi-card {cssClass}\"><span class=\"kpi-value\">{value}</span><span class=\"kpi-label\">{Encode(label)}</span></div>");
    }

    // ── Environment Inventory ───────────────────────────────

    private static void AppendEnvironmentInventory(StringBuilder sb, RiskReport report)
    {
        sb.AppendLine("<section class=\"env-inventory\">");
        sb.AppendLine("<h2>Environment Inventory</h2>");
        sb.AppendLine("<div class=\"table-scroll\">");
        sb.AppendLine("<table><thead><tr>");
        sb.AppendLine("<th>Environment</th><th>Type</th><th>Solutions</th><th>Components</th><th>Workflows</th><th>Plugins</th><th>SDK Steps</th><th>Web Resources</th><th>Conn. Refs</th><th>Env Vars</th><th>Business Rules</th><th>Connectors</th><th>Endpoints</th><th>Forms</th><th>Views</th><th>Charts</th><th>Apps</th><th>Sec. Roles</th><th>Field Sec.</th><th>Entities</th>");
        sb.AppendLine("</tr></thead><tbody>");

        foreach (var env in report.EnvironmentSummaries)
        {
            sb.Append(CultureInfo.InvariantCulture,
                $"<tr><td><a href=\"{Encode(env.EnvironmentUrl.ToString())}\" target=\"_blank\" rel=\"noopener\">{Encode(env.EnvironmentDisplayName)}</a></td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{Encode(env.EnvironmentType.ToString())}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{env.Solutions}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{env.Components}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{env.Workflows}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{env.PluginAssemblies}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{env.SdkSteps}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{env.WebResources}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{env.ConnectionReferences}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{env.EnvironmentVariables}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{env.BusinessRules}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{env.CustomConnectors}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{env.ServiceEndpoints}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{env.Forms}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{env.Views}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{env.Charts}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{env.AppModules}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{env.SecurityRoles}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{env.FieldSecurityProfiles}</td>");
            sb.AppendLine(CultureInfo.InvariantCulture, $"<td>{env.Entities}</td></tr>");
        }

        sb.AppendLine("</tbody></table>");
        sb.AppendLine("</div>");
        sb.AppendLine("</section>");
    }

    private static void AppendEnvironmentsList(StringBuilder sb, RiskReport report)
    {
        sb.AppendLine("<section class=\"environments\">");
        sb.AppendLine("<h2>Compared Environments</h2>");
        sb.AppendLine("<ul>");
        foreach (var env in report.ComparedEnvironments)
        {
            sb.AppendLine(CultureInfo.InvariantCulture,
                $"<li><strong>{Encode(env.DisplayName)}</strong> &mdash; <a href=\"{Encode(env.EnvironmentUrl.ToString())}\" target=\"_blank\" rel=\"noopener\"><code>{Encode(env.EnvironmentUrl.ToString())}</code></a></li>");
        }
        sb.AppendLine("</ul>");
        sb.AppendLine("</section>");
    }

    // ── Solution Breakdown ──────────────────────────────────

    private static void AppendSolutionBreakdown(StringBuilder sb, RiskReport report)
    {
        if (report.SolutionInventories.Count == 0)
        {
            return;
        }

        sb.AppendLine("<section class=\"solution-breakdown\">");
        sb.AppendLine("<h2>Solution Breakdown</h2>");
        sb.AppendLine("<p class=\"meta\">Solutions grouped by origin. <strong>Custom</strong> solutions are highlighted.</p>");

        foreach (var inv in report.SolutionInventories)
        {
            var custom = inv.Solutions.Where(s => !s.IsMicrosoft).ToList();
            var msft = inv.Solutions.Where(s => s.IsMicrosoft).ToList();

            // Custom solutions first
            if (custom.Count > 0)
            {
                sb.AppendLine("<details open>");
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"<summary><h3>Custom Solutions ({custom.Count})</h3></summary>");
                AppendSolutionTable(sb, custom);
                sb.AppendLine("</details>");
            }

            // Microsoft solutions (collapsed)
            if (msft.Count > 0)
            {
                sb.AppendLine("<details>");
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"<summary><h3>Microsoft Solutions ({msft.Count})</h3></summary>");
                AppendSolutionTable(sb, msft);
                sb.AppendLine("</details>");
            }
        }

        sb.AppendLine("</section>");
    }

    private static void AppendSolutionTable(StringBuilder sb, List<SolutionBreakdown> solutions)
    {
        sb.AppendLine("<div class=\"table-scroll\">");
        sb.AppendLine("<table><thead><tr>");
        sb.AppendLine("<th>Solution</th><th>Publisher</th><th>Version</th><th>Managed</th><th>Total</th><th>Entities</th><th>Forms</th><th>Views</th><th>Workflows</th><th>Plugins</th><th>Web Res.</th><th>Roles</th><th>Other</th>");
        sb.AppendLine("</tr></thead><tbody>");

        foreach (var sol in solutions)
        {
            sb.Append(CultureInfo.InvariantCulture,
                $"<tr><td title=\"{Encode(sol.UniqueName)}\"><strong>{Encode(sol.DisplayName)}</strong></td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{Encode(sol.PublisherName)}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{Encode(sol.Version)}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{(sol.IsManaged ? "Yes" : "No")}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td><strong>{sol.TotalComponents}</strong></td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{sol.Entities}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{sol.Forms}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{sol.Views}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{sol.Workflows}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{sol.PluginAssemblies}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{sol.WebResources}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{sol.Roles}</td>");
            sb.AppendLine(CultureInfo.InvariantCulture, $"<td>{sol.OtherComponents}</td></tr>");
        }

        sb.AppendLine("</tbody></table>");
        sb.AppendLine("</div>");
    }

    // ── Custom Artifacts ────────────────────────────────────

    private static void AppendCustomArtifacts(StringBuilder sb, RiskReport report)
    {
        if (report.CustomArtifactSummaries.Count == 0)
        {
            return;
        }

        sb.AppendLine("<section class=\"custom-artifacts\">");
        sb.AppendLine("<h2>Custom Artifact Details</h2>");
        sb.AppendLine("<p class=\"meta\">Non-Microsoft artifacts found in the environment. Use these details to understand what custom components exist.</p>");

        foreach (var summary in report.CustomArtifactSummaries)
        {
            // App Modules
            if (summary.AppModules.Count > 0)
            {
                sb.AppendLine("<details open>");
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"<summary><h3>App Modules ({summary.AppModules.Count})</h3></summary>");
                sb.AppendLine("<div class=\"table-scroll\"><table><thead><tr><th>Name</th><th>Unique Name</th><th>Published</th><th>Managed</th></tr></thead><tbody>");
                foreach (var app in summary.AppModules)
                {
                    sb.AppendLine(CultureInfo.InvariantCulture,
                        $"<tr><td>{Encode(app.Name)}</td><td>{Encode(app.UniqueName)}</td><td>{(app.IsPublished ? "Yes" : "No")}</td><td>{(app.IsManaged ? "Yes" : "No")}</td></tr>");
                }
                sb.AppendLine("</tbody></table></div></details>");
            }

            // Connection References (non-Microsoft)
            if (summary.ConnectionReferences.Count > 0)
            {
                sb.AppendLine("<details open>");
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"<summary><h3>Connection References ({summary.ConnectionReferences.Count})</h3></summary>");
                sb.AppendLine("<div class=\"table-scroll\"><table><thead><tr><th>Logical Name</th><th>Display Name</th><th>Connector</th><th>Connected</th></tr></thead><tbody>");
                foreach (var cr in summary.ConnectionReferences)
                {
                    var connected = cr.HasConnection ? "<span class=\"tag low\">Yes</span>" : "<span class=\"tag high\">No</span>";
                    sb.AppendLine(CultureInfo.InvariantCulture,
                        $"<tr><td>{Encode(cr.LogicalName)}</td><td>{Encode(cr.DisplayName ?? "")}</td><td>{Encode(cr.ConnectorId ?? "")}</td><td>{connected}</td></tr>");
                }
                sb.AppendLine("</tbody></table></div></details>");
            }

            // Workflows (unmanaged)
            if (summary.Workflows.Count > 0)
            {
                sb.AppendLine("<details>");
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"<summary><h3>Custom Workflows &amp; Flows ({summary.Workflows.Count})</h3></summary>");
                sb.AppendLine("<div class=\"table-scroll\"><table><thead><tr><th>Name</th><th>Category</th><th>Active</th></tr></thead><tbody>");
                foreach (var wf in summary.Workflows)
                {
                    var active = wf.IsActivated ? "<span class=\"tag low\">Yes</span>" : "<span class=\"tag medium\">No</span>";
                    sb.AppendLine(CultureInfo.InvariantCulture,
                        $"<tr><td>{Encode(wf.Name)}</td><td>{Encode(wf.Category)}</td><td>{active}</td></tr>");
                }
                sb.AppendLine("</tbody></table></div></details>");
            }

            // Plugins
            if (summary.Plugins.Count > 0)
            {
                sb.AppendLine("<details>");
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"<summary><h3>Plugin Assemblies ({summary.Plugins.Count})</h3></summary>");
                sb.AppendLine("<div class=\"table-scroll\"><table><thead><tr><th>Name</th><th>Version</th><th>Isolation</th></tr></thead><tbody>");
                foreach (var p in summary.Plugins)
                {
                    sb.AppendLine(CultureInfo.InvariantCulture,
                        $"<tr><td>{Encode(p.Name)}</td><td>{Encode(p.Version ?? "")}</td><td>{Encode(p.IsolationMode)}</td></tr>");
                }
                sb.AppendLine("</tbody></table></div></details>");
            }

            // Forms (unmanaged)
            if (summary.Forms.Count > 0)
            {
                sb.AppendLine("<details>");
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"<summary><h3>Custom Forms ({summary.Forms.Count})</h3></summary>");
                sb.AppendLine("<div class=\"table-scroll\"><table><thead><tr><th>Entity</th><th>Name</th><th>Type</th></tr></thead><tbody>");
                foreach (var f in summary.Forms)
                {
                    sb.AppendLine(CultureInfo.InvariantCulture,
                        $"<tr><td>{Encode(f.Entity)}</td><td>{Encode(f.Name)}</td><td>{Encode(f.FormType)}</td></tr>");
                }
                sb.AppendLine("</tbody></table></div></details>");
            }

            // Custom Entities
            if (summary.Entities.Count > 0)
            {
                sb.AppendLine("<details>");
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"<summary><h3>Custom / Customized Entities ({summary.Entities.Count})</h3></summary>");
                sb.AppendLine("<div class=\"table-scroll\"><table><thead><tr><th>Logical Name</th><th>Display Name</th><th>Custom</th><th>Managed</th></tr></thead><tbody>");
                foreach (var e in summary.Entities)
                {
                    sb.AppendLine(CultureInfo.InvariantCulture,
                        $"<tr><td>{Encode(e.LogicalName)}</td><td>{Encode(e.DisplayName ?? "")}</td><td>{(e.IsCustom ? "Yes" : "No")}</td><td>{(e.IsManaged ? "Yes" : "No")}</td></tr>");
                }
                sb.AppendLine("</tbody></table></div></details>");
            }

            // Web Resources (unmanaged, capped at 100)
            if (summary.WebResources.Count > 0)
            {
                sb.AppendLine("<details>");
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"<summary><h3>Custom Web Resources ({summary.WebResources.Count})</h3></summary>");
                sb.AppendLine("<div class=\"table-scroll\"><table><thead><tr><th>Name</th><th>Type</th></tr></thead><tbody>");
                foreach (var w in summary.WebResources)
                {
                    sb.AppendLine(CultureInfo.InvariantCulture,
                        $"<tr><td>{Encode(w.Name)}</td><td>{Encode(w.Type)}</td></tr>");
                }
                sb.AppendLine("</tbody></table></div></details>");
            }
        }

        sb.AppendLine("</section>");
    }

    // ── Executive Summary ───────────────────────────────────

    private static void AppendExecutiveSummary(StringBuilder sb, RiskReport report)
    {
        sb.AppendLine("<section class=\"executive-summary\">");
        sb.AppendLine("<h2>Executive Summary</h2>");

        var observations = new List<string>();

        // Platform info
        foreach (var ss in report.SettingsSnapshots)
        {
            if (!string.IsNullOrEmpty(ss.DataverseVersion))
            {
                observations.Add($"Dataverse platform version <strong>{Encode(ss.DataverseVersion)}</strong>.");
            }

            if (ss.ScanDuration.HasValue)
            {
                observations.Add($"Snapshot captured in <strong>{ss.ScanDuration.Value.TotalSeconds:F0}s</strong>.");
            }
        }

        // Solution landscape
        foreach (var inv in report.SolutionInventories)
        {
            var custom = inv.Solutions.Where(s => !s.IsMicrosoft).ToList();
            var msft = inv.Solutions.Where(s => s.IsMicrosoft).ToList();
            var totalCustomComponents = custom.Sum(s => s.TotalComponents);

            observations.Add($"<strong>{custom.Count}</strong> custom solution(s) with <strong>{totalCustomComponents.ToString("N0", CultureInfo.InvariantCulture)}</strong> components, alongside <strong>{msft.Count}</strong> Microsoft solution(s).");

            // Default solution warning
            var defaultSol = inv.Solutions.FirstOrDefault(s =>
                s.UniqueName.Equals("Default", StringComparison.OrdinalIgnoreCase));
            if (defaultSol is not null && defaultSol.TotalComponents > 1000)
            {
                observations.Add($"&#9888; The <strong>Default Solution</strong> contains <strong>{defaultSol.TotalComponents.ToString("N0", CultureInfo.InvariantCulture)}</strong> components &mdash; this indicates significant unmanaged customization that should be moved into dedicated solutions for ALM governance.");
            }
        }

        // Settings highlights
        foreach (var ss in report.SettingsSnapshots)
        {
            var auditOff = ss.Settings.FirstOrDefault(s => s.Key == "isauditenabled");
            if (auditOff is { Value: "False" or "false" })
            {
                observations.Add("&#9888; <strong>Organization auditing is disabled.</strong> Consider enabling it for compliance and traceability.");
            }

            var pluginTrace = ss.Settings.FirstOrDefault(s => s.Key == "plugintracelogsetting");
            if (pluginTrace is { Value: "2" })
            {
                observations.Add("&#9888; Plugin trace logging is set to <strong>All</strong>. This causes performance overhead &mdash; set to <em>Exception</em> in production.");
            }
            else if (pluginTrace is { Value: "0" })
            {
                observations.Add("Plugin trace logging is <strong>Off</strong>. Consider setting to <em>Exception</em> for troubleshooting support.");
            }

            var sessionTimeout = ss.Settings.FirstOrDefault(s => s.Key == "sessiontimeoutenabled");
            if (sessionTimeout is { Value: "False" or "false" })
            {
                observations.Add("Session timeout is <strong>not enforced</strong>. Consider enabling for security compliance.");
            }
        }

        // Plugin registration insights
        foreach (var map in report.PluginMaps)
        {
            if (map.TotalSteps > 0)
            {
                observations.Add($"<strong>{map.TotalSteps}</strong> custom plugin step(s) registered ({map.SyncSteps} sync, {map.AsyncSteps} async){(map.DisabledSteps > 0 ? $", <strong>{map.DisabledSteps} disabled</strong>" : "")}.");
            }
        }

        // Security posture insights
        foreach (var posture in report.SecurityPostures)
        {
            if (posture.UnmanagedRoleCount > 0)
            {
                observations.Add($"&#9888; <strong>{posture.UnmanagedRoleCount}</strong> unmanaged security role(s) detected &mdash; these should be managed in solutions for proper ALM.");
            }
        }

        // Environment variable insights
        foreach (var inv in report.EnvironmentVariableInventories)
        {
            if (inv.MissingValueCount > 0)
            {
                observations.Add($"&#9888; <strong>{inv.MissingValueCount}</strong> environment variable(s) missing values &mdash; may cause runtime failures.");
            }
        }

        // Entity governance insights
        foreach (var gov in report.EntityGovernances)
        {
            if (gov.TotalCustomEntities > 0)
            {
                var auditPct = gov.AuditEnabledCount * 100 / gov.TotalCustomEntities;
                if (auditPct < 50)
                {
                    observations.Add($"&#9888; Only <strong>{auditPct}%</strong> of {gov.TotalCustomEntities} custom entities have auditing enabled &mdash; compliance gap.");
                }
            }
        }

        // Risk summary
        var level = report.OverallRiskLevel;
        var score = report.OverallRiskScore;
        observations.Add($"Overall risk assessment: <strong>{level}</strong> ({score}/100) with <strong>{report.Findings.Count}</strong> finding(s).");

        sb.AppendLine("<ul class=\"exec-observations\">");
        foreach (var obs in observations)
        {
            sb.AppendLine($"<li>{obs}</li>");
        }

        sb.AppendLine("</ul>");
        sb.AppendLine("</section>");
    }

    // ── Organization Settings Audit ─────────────────────────

    private static void AppendSettingsAudit(StringBuilder sb, RiskReport report)
    {
        if (report.SettingsSnapshots.Count == 0)
        {
            return;
        }

        sb.AppendLine("<section class=\"settings-audit\">");
        sb.AppendLine("<h2>Organization Settings</h2>");
        sb.AppendLine("<p class=\"meta\">Key configuration values from the Dataverse Organization entity. Review for security and governance compliance.</p>");

        foreach (var ss in report.SettingsSnapshots)
        {
            if (ss.Settings.Count == 0)
            {
                continue;
            }

            sb.AppendLine("<div class=\"table-scroll\">");
            sb.AppendLine("<table><thead><tr><th>Category</th><th>Setting</th><th>Value</th><th>Assessment</th></tr></thead><tbody>");

            foreach (var setting in ss.Settings.OrderBy(s => s.Category, StringComparer.OrdinalIgnoreCase).ThenBy(s => s.Key, StringComparer.OrdinalIgnoreCase))
            {
                var (displayValue, assessment) = AssessSettingValue(setting);
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"<tr><td>{Encode(setting.Category)}</td><td title=\"{Encode(setting.Description ?? "")}\">{Encode(setting.Key)}</td><td><code>{Encode(displayValue)}</code></td><td>{assessment}</td></tr>");
            }

            sb.AppendLine("</tbody></table>");
            sb.AppendLine("</div>");
        }

        sb.AppendLine("</section>");
    }

    private static (string DisplayValue, string Assessment) AssessSettingValue(EnvironmentSetting setting)
    {
        var raw = setting.Value ?? "(null)";

        return setting.Key switch
        {
            "isauditenabled" => raw is "True" or "true"
                ? (raw, "<span class=\"tag low\">OK</span>")
                : (raw, "<span class=\"tag high\">Review</span>"),

            "isuseraccessauditenabled" => raw is "True" or "true"
                ? (raw, "<span class=\"tag low\">OK</span>")
                : (raw, "<span class=\"tag medium\">Review</span>"),

            "plugintracelogsetting" => raw switch
            {
                "0" => ("Off", "<span class=\"tag info\">Off</span>"),
                "1" => ("Exception", "<span class=\"tag low\">OK</span>"),
                "2" => ("All", "<span class=\"tag high\">Performance risk</span>"),
                _ => (raw, "<span class=\"tag info\">&mdash;</span>")
            },

            "sessiontimeoutenabled" => raw is "True" or "true"
                ? (raw, "<span class=\"tag low\">OK</span>")
                : (raw, "<span class=\"tag medium\">Review</span>"),

            "maxuploadfilesize" => int.TryParse(raw, CultureInfo.InvariantCulture, out var sizeKb)
                ? ($"{sizeKb / 1024} MB", sizeKb > 131_072 ? "<span class=\"tag medium\">Large</span>" : "<span class=\"tag low\">OK</span>")
                : (raw, "<span class=\"tag info\">&mdash;</span>"),

            "blockedattachments" => string.IsNullOrWhiteSpace(raw) || raw == "(null)"
                ? ("(none)", "<span class=\"tag high\">No blocklist</span>")
                : (raw.Length > 60 ? raw[..60] + "..." : raw, "<span class=\"tag low\">OK</span>"),

            _ => (raw, "<span class=\"tag info\">&mdash;</span>")
        };
    }

    private static string BuildVersionBadge(RiskReport report)
    {
        var version = report.SettingsSnapshots
            .Select(s => s.DataverseVersion)
            .FirstOrDefault(v => !string.IsNullOrEmpty(v));

        return version is not null
            ? $" &middot; Dataverse v{Encode(version)}"
            : "";
    }

    // ── Plugin Registration Map ─────────────────────────────

    private static void AppendPluginRegistrationMap(StringBuilder sb, RiskReport report)
    {
        if (report.PluginMaps.Count == 0)
        {
            return;
        }

        sb.AppendLine("<section class=\"plugin-map\">");
        sb.AppendLine("<h2>Plugin Registration Map</h2>");
        sb.AppendLine("<p class=\"meta\">Non-Microsoft SDK message processing steps grouped by plugin type. Shows event pipeline registration details.</p>");

        foreach (var map in report.PluginMaps)
        {
            if (map.TotalSteps == 0)
            {
                sb.AppendLine("<p class=\"meta\">No custom plugin steps registered.</p>");
                continue;
            }

            // KPI row
            sb.AppendLine("<div class=\"mini-kpi-row\">");
            sb.AppendLine(CultureInfo.InvariantCulture, $"<span class=\"mini-kpi\"><strong>{map.TotalSteps}</strong> Total Steps</span>");
            sb.AppendLine(CultureInfo.InvariantCulture, $"<span class=\"mini-kpi\"><strong>{map.SyncSteps}</strong> Sync</span>");
            sb.AppendLine(CultureInfo.InvariantCulture, $"<span class=\"mini-kpi\"><strong>{map.AsyncSteps}</strong> Async</span>");
            if (map.DisabledSteps > 0)
            {
                sb.AppendLine(CultureInfo.InvariantCulture, $"<span class=\"mini-kpi warn\"><strong>{map.DisabledSteps}</strong> Disabled</span>");
            }
            sb.AppendLine("</div>");

            foreach (var group in map.PluginGroups)
            {
                sb.AppendLine("<details>");
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"<summary><h3>{Encode(group.PluginName)} ({group.Steps.Count} step{(group.Steps.Count == 1 ? "" : "s")})</h3></summary>");
                sb.AppendLine("<div class=\"table-scroll\"><table><thead><tr><th>Message</th><th>Entity</th><th>Stage</th><th>Mode</th><th>Status</th></tr></thead><tbody>");
                foreach (var step in group.Steps)
                {
                    var status = step.IsDisabled
                        ? "<span class=\"tag medium\">Disabled</span>"
                        : "<span class=\"tag low\">Active</span>";
                    var mode = step.Mode == "Synchronous"
                        ? $"<span class=\"tag high\">Sync</span>"
                        : $"<span class=\"tag info\">Async</span>";
                    sb.AppendLine(CultureInfo.InvariantCulture,
                        $"<tr><td>{Encode(step.Message ?? "")}</td><td>{Encode(step.Entity ?? "none")}</td><td>{Encode(step.Stage)}</td><td>{mode}</td><td>{status}</td></tr>");
                }
                sb.AppendLine("</tbody></table></div></details>");
            }
        }

        sb.AppendLine("</section>");
    }

    // ── Security Posture ────────────────────────────────────

    private static void AppendSecurityPosture(StringBuilder sb, RiskReport report)
    {
        if (report.SecurityPostures.Count == 0)
        {
            return;
        }

        sb.AppendLine("<section class=\"security-posture\">");
        sb.AppendLine("<h2>Security Posture</h2>");
        sb.AppendLine("<p class=\"meta\">Security roles and field security profiles. Unmanaged roles indicate custom security configuration that needs governance.</p>");

        foreach (var posture in report.SecurityPostures)
        {
            // KPI row
            sb.AppendLine("<div class=\"mini-kpi-row\">");
            sb.AppendLine(CultureInfo.InvariantCulture, $"<span class=\"mini-kpi\"><strong>{posture.TotalRoles}</strong> Total Roles</span>");
            if (posture.UnmanagedRoleCount > 0)
            {
                sb.AppendLine(CultureInfo.InvariantCulture, $"<span class=\"mini-kpi warn\"><strong>{posture.UnmanagedRoleCount}</strong> Unmanaged</span>");
            }
            sb.AppendLine(CultureInfo.InvariantCulture, $"<span class=\"mini-kpi\"><strong>{posture.SystemRoles.Count}</strong> Managed</span>");
            sb.AppendLine(CultureInfo.InvariantCulture, $"<span class=\"mini-kpi\"><strong>{posture.FieldSecurityProfiles.Count}</strong> Field Security Profiles</span>");
            sb.AppendLine("</div>");

            // Custom (unmanaged) roles
            if (posture.CustomRoles.Count > 0)
            {
                sb.AppendLine("<details open>");
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"<summary><h3>Custom / Unmanaged Roles ({posture.CustomRoles.Count})</h3></summary>");
                sb.AppendLine("<div class=\"table-scroll\"><table><thead><tr><th>Name</th><th>Business Unit</th><th>Customizable</th><th>Last Modified</th></tr></thead><tbody>");
                foreach (var role in posture.CustomRoles)
                {
                    var modified = role.ModifiedOn?.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture) ?? "";
                    sb.AppendLine(CultureInfo.InvariantCulture,
                        $"<tr><td>{Encode(role.Name)}</td><td>{Encode(role.BusinessUnit ?? "")}</td><td>{(role.IsCustomizable ? "Yes" : "No")}</td><td>{modified}</td></tr>");
                }
                sb.AppendLine("</tbody></table></div></details>");
            }

            // Field security profiles
            if (posture.FieldSecurityProfiles.Count > 0)
            {
                sb.AppendLine("<details>");
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"<summary><h3>Field Security Profiles ({posture.FieldSecurityProfiles.Count})</h3></summary>");
                sb.AppendLine("<div class=\"table-scroll\"><table><thead><tr><th>Name</th><th>Managed</th><th>Description</th></tr></thead><tbody>");
                foreach (var fsp in posture.FieldSecurityProfiles)
                {
                    sb.AppendLine(CultureInfo.InvariantCulture,
                        $"<tr><td>{Encode(fsp.Name)}</td><td>{(fsp.IsManaged ? "Yes" : "No")}</td><td>{Encode(fsp.Description ?? "")}</td></tr>");
                }
                sb.AppendLine("</tbody></table></div></details>");
            }
        }

        sb.AppendLine("</section>");
    }

    // ── Environment Variables ───────────────────────────────

    private static void AppendEnvironmentVariables(StringBuilder sb, RiskReport report)
    {
        if (report.EnvironmentVariableInventories.Count == 0)
        {
            return;
        }

        sb.AppendLine("<section class=\"env-variables\">");
        sb.AppendLine("<h2>Environment Variables</h2>");
        sb.AppendLine("<p class=\"meta\">Environment variable definitions and their value status. Missing values may cause runtime failures.</p>");

        foreach (var inv in report.EnvironmentVariableInventories)
        {
            if (inv.Variables.Count == 0)
            {
                sb.AppendLine("<p class=\"meta\">No environment variables defined.</p>");
                continue;
            }

            // KPI row
            sb.AppendLine("<div class=\"mini-kpi-row\">");
            sb.AppendLine(CultureInfo.InvariantCulture, $"<span class=\"mini-kpi\"><strong>{inv.Variables.Count}</strong> Variables</span>");
            if (inv.MissingValueCount > 0)
            {
                sb.AppendLine(CultureInfo.InvariantCulture, $"<span class=\"mini-kpi warn\"><strong>{inv.MissingValueCount}</strong> Missing Value</span>");
            }
            sb.AppendLine("</div>");

            sb.AppendLine("<div class=\"table-scroll\"><table><thead><tr><th>Schema Name</th><th>Display Name</th><th>Type</th><th>Has Value</th><th>Required</th><th>Solution</th></tr></thead><tbody>");
            foreach (var v in inv.Variables)
            {
                var hasVal = v.HasValue
                    ? "<span class=\"tag low\">Yes</span>"
                    : "<span class=\"tag high\">No</span>";
                var required = v.IsRequired ? "Yes" : "";
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"<tr><td><code>{Encode(v.SchemaName)}</code></td><td>{Encode(v.DisplayName ?? "")}</td><td>{Encode(v.Type)}</td><td>{hasVal}</td><td>{required}</td><td>{Encode(v.SolutionName ?? "")}</td></tr>");
            }
            sb.AppendLine("</tbody></table></div>");
        }

        sb.AppendLine("</section>");
    }

    // ── Entity Governance ───────────────────────────────────

    private static void AppendEntityGovernance(StringBuilder sb, RiskReport report)
    {
        if (report.EntityGovernances.Count == 0)
        {
            return;
        }

        sb.AppendLine("<section class=\"entity-governance\">");
        sb.AppendLine("<h2>Entity Governance</h2>");
        sb.AppendLine("<p class=\"meta\">Custom entity audit and change tracking coverage. Entities without audit enabled may create compliance gaps.</p>");

        foreach (var gov in report.EntityGovernances)
        {
            if (gov.TotalCustomEntities == 0)
            {
                sb.AppendLine("<p class=\"meta\">No custom entities found.</p>");
                continue;
            }

            var auditPct = gov.TotalCustomEntities > 0
                ? (gov.AuditEnabledCount * 100 / gov.TotalCustomEntities)
                : 0;
            var ctPct = gov.TotalCustomEntities > 0
                ? (gov.ChangeTrackingEnabledCount * 100 / gov.TotalCustomEntities)
                : 0;

            // KPI row (covers all custom entities including Microsoft)
            sb.AppendLine("<div class=\"mini-kpi-row\">");
            sb.AppendLine(CultureInfo.InvariantCulture, $"<span class=\"mini-kpi\"><strong>{gov.TotalCustomEntities}</strong> Custom Entities (all)</span>");
            var auditClass = auditPct < 50 ? " warn" : "";
            sb.AppendLine(CultureInfo.InvariantCulture, $"<span class=\"mini-kpi{auditClass}\"><strong>{auditPct}%</strong> Audit Enabled</span>");
            sb.AppendLine(CultureInfo.InvariantCulture, $"<span class=\"mini-kpi\"><strong>{ctPct}%</strong> Change Tracking</span>");
            if (gov.Entities.Count > 0)
            {
                sb.AppendLine(CultureInfo.InvariantCulture, $"<span class=\"mini-kpi\"><strong>{gov.Entities.Count}</strong> Your Custom Entities</span>");
            }
            sb.AppendLine("</div>");

            // Detail table for non-Microsoft custom entities only
            if (gov.Entities.Count > 0)
            {
                sb.AppendLine("<details>");
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"<summary><h3>Your Custom Entities ({gov.Entities.Count})</h3></summary>");
                sb.AppendLine("<div class=\"table-scroll\"><table><thead><tr><th>Logical Name</th><th>Display Name</th><th>Audit</th><th>Change Tracking</th><th>Ownership</th><th>Columns</th></tr></thead><tbody>");
                foreach (var e in gov.Entities)
                {
                    var audit = e.IsAuditEnabled
                        ? "<span class=\"tag low\">On</span>"
                        : "<span class=\"tag high\">Off</span>";
                    var ct = e.ChangeTrackingEnabled
                        ? "<span class=\"tag low\">On</span>"
                        : "<span class=\"tag medium\">Off</span>";
                    sb.AppendLine(CultureInfo.InvariantCulture,
                        $"<tr><td><code>{Encode(e.LogicalName)}</code></td><td>{Encode(e.DisplayName ?? "")}</td><td>{audit}</td><td>{ct}</td><td>{Encode(e.OwnershipType)}</td><td>{e.AttributeCount?.ToString(CultureInfo.InvariantCulture) ?? ""}</td></tr>");
                }
                sb.AppendLine("</tbody></table></div></details>");
            }
            else
            {
                sb.AppendLine("<p class=\"meta\">No non-Microsoft custom entities found. All custom entities are part of Microsoft solutions.</p>");
            }
        }

        sb.AppendLine("</section>");
    }

    // ── Severity Section ────────────────────────────────────

    private static void AppendSeveritySection(StringBuilder sb, RiskReport report)
    {
        if (report.SeverityCounts.Count == 0)
        {
            return;
        }

        sb.AppendLine("<section class=\"severity-summary\">");
        sb.AppendLine("<h2>Severity Breakdown</h2>");
        sb.AppendLine("<div class=\"chart-container\"><canvas id=\"severityChart\"></canvas></div>");

        // Fallback table (also useful for no-JS)
        sb.AppendLine("<table class=\"severity-table\"><thead><tr><th>Severity</th><th>Count</th></tr></thead><tbody>");
        foreach (var severity in Enum.GetValues<Severity>().OrderByDescending(s => s))
        {
            if (report.SeverityCounts.TryGetValue(severity, out var count) && count > 0)
            {
                var sevClass = severity.ToString().ToLowerInvariant();
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"<tr><td><span class=\"tag {sevClass}\">{severity}</span></td><td>{count}</td></tr>");
            }
        }
        sb.AppendLine("</tbody></table>");
        sb.AppendLine("</section>");
    }

    // ── Analysis Coverage ───────────────────────────────────

    private static void AppendAnalysisCoverage(StringBuilder sb, RiskReport report)
    {
        var categoryCounts = report.Findings
            .GroupBy(f => f.Category)
            .ToDictionary(g => g.Key, g => g.Count());
        var envCount = report.ComparedEnvironments.Count;
        var hasProdLike = report.ComparedEnvironments.Any(e =>
            e.EnvironmentType is EnvironmentType.Prod or EnvironmentType.Staging);

        sb.AppendLine("<section class=\"analysis-coverage\">");
        sb.AppendLine("<h2>Analysis Coverage</h2>");

        // Chart
        sb.AppendLine("<div class=\"chart-container\"><canvas id=\"categoryChart\"></canvas></div>");

        sb.AppendLine("<div class=\"table-scroll\">");
        sb.AppendLine("<table><thead><tr><th>Category</th><th>Scope</th><th>Applicable</th><th>Findings</th></tr></thead><tbody>");

        // Show applicable categories first, then non-applicable collapsed
        var allCategories = Enum.GetValues<FindingCategory>().OrderBy(c => c.ToString(), StringComparer.Ordinal).ToList();
        var applicableCategories = allCategories.Where(c => CategoryHelper.IsCategoryApplicable(c, envCount, hasProdLike) || categoryCounts.ContainsKey(c)).ToList();
        var nonApplicable = allCategories.Except(applicableCategories).ToList();

        foreach (var category in applicableCategories)
        {
            categoryCounts.TryGetValue(category, out var count);
            var scope = CategoryHelper.GetCategoryScope(category);
            sb.AppendLine(CultureInfo.InvariantCulture,
                $"<tr><td>{Encode(category.ToString())}</td><td>{Encode(scope)}</td><td>yes</td><td>{count}</td></tr>");
        }

        sb.AppendLine("</tbody></table>");
        sb.AppendLine("</div>");
        if (nonApplicable.Count > 0)
        {
            sb.AppendLine(CultureInfo.InvariantCulture,
                $"<p class=\"meta\">{nonApplicable.Count} additional check(s) not applicable to the current run shape (e.g. cross-environment checks require 2+ environments).</p>");
        }
        sb.AppendLine("</section>");
    }

    // ── Findings ────────────────────────────────────────────

    private static void AppendFindings(StringBuilder sb, RiskReport report)
    {
        if (report.Findings.Count == 0)
        {
            return;
        }

        sb.AppendLine("<section class=\"findings\">");
        sb.AppendLine("<h2>Findings</h2>");
        sb.AppendLine("<div class=\"filter-bar\">");
        sb.AppendLine("<input id=\"findingSearch\" type=\"text\" placeholder=\"Filter findings\u2026\" class=\"filter-input\" aria-label=\"Filter findings\">");
        sb.AppendLine("<select id=\"severityFilter\" class=\"filter-select\" aria-label=\"Filter by severity\">");
        sb.AppendLine("<option value=\"\">All Severities</option>");
        foreach (var sev in Enum.GetValues<Severity>().OrderByDescending(s => s))
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"<option value=\"{sev.ToString().ToLowerInvariant()}\">{sev}</option>");
        }
        sb.AppendLine("</select>");
        sb.AppendLine("</div>");

        // Build annotation lookup for AI enrichment
        var annotations = BuildAnnotationLookup(report);

        var grouped = report.Findings
            .GroupBy(f => f.Category)
            .OrderByDescending(g => g.Max(f => f.RiskScore ?? 0));

        foreach (var group in grouped)
        {
            sb.AppendLine("<details open>");
            sb.AppendLine(CultureInfo.InvariantCulture,
                $"<summary><h3>{Encode(group.Key.ToString())} ({group.Count()})</h3></summary>");

            foreach (var finding in group.OrderByDescending(f => f.Severity))
            {
                var sevClass = finding.Severity.ToString().ToLowerInvariant();
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"<div class=\"finding\" data-severity=\"{sevClass}\" data-text=\"{Encode(finding.Title.ToLowerInvariant())} {Encode(finding.Description.ToLowerInvariant())}\">");
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"  <h4><span class=\"tag {sevClass}\">{finding.Severity}</span> {Encode(finding.Title)}</h4>");
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"  <p>{Encode(finding.Description)}</p>");

                if (finding.RiskScore.HasValue)
                {
                    sb.AppendLine(CultureInfo.InvariantCulture,
                        $"  <p class=\"score-line\">Risk Score: <strong>{finding.RiskScore}</strong></p>");
                }

                if (finding.AffectedEnvironments.Count > 0)
                {
                    sb.AppendLine(CultureInfo.InvariantCulture,
                        $"  <p class=\"affected\">Affected: {Encode(string.Join(", ", finding.AffectedEnvironments))}</p>");
                }

                if (finding.RuleId is not null)
                {
                    sb.AppendLine(CultureInfo.InvariantCulture,
                        $"  <p class=\"rule\">Rule: <code>{Encode(finding.RuleId)}</code></p>");
                }

                // Deep link
                var deepLink = DeepLinkBuilder.TryBuildLink(finding.Details);
                if (deepLink is not null)
                {
                    sb.AppendLine(CultureInfo.InvariantCulture,
                        $"  <p class=\"deep-link\"><a href=\"{Encode(deepLink)}\" target=\"_blank\" rel=\"noopener\">Open in Dynamics 365 &#8599;</a></p>");
                }

                // Details table
                if (finding.Details.Count > 0)
                {
                    sb.AppendLine("  <details class=\"details-toggle\">");
                    sb.AppendLine("  <summary>Details</summary>");
                    sb.AppendLine("  <table class=\"details-table\"><tbody>");
                    foreach (var (key, value) in finding.Details)
                    {
                        sb.AppendLine(CultureInfo.InvariantCulture,
                            $"    <tr><td class=\"detail-key\">{Encode(key)}</td><td>{Encode(value)}</td></tr>");
                    }
                    sb.AppendLine("  </tbody></table>");
                    sb.AppendLine("  </details>");
                }

                // AI annotation for this finding
                if (annotations.TryGetValue(finding.FindingId, out var annotation))
                {
                    sb.AppendLine("  <div class=\"ai-annotation\">");
                    sb.AppendLine("    <span class=\"ai-badge\">AI</span>");
                    if (!string.IsNullOrWhiteSpace(annotation.Commentary))
                    {
                        sb.AppendLine(CultureInfo.InvariantCulture,
                            $"    <p class=\"ai-commentary\">{Encode(annotation.Commentary)}</p>");
                    }
                    if (annotation.SuggestedActions.Count > 0)
                    {
                        sb.AppendLine("    <ul class=\"ai-actions\">");
                        foreach (var action in annotation.SuggestedActions)
                        {
                            sb.AppendLine(CultureInfo.InvariantCulture,
                                $"      <li>{Encode(action)}</li>");
                        }
                        sb.AppendLine("    </ul>");
                    }
                    sb.AppendLine("  </div>");
                }

                sb.AppendLine("</div>");
            }

            sb.AppendLine("</details>");
        }

        sb.AppendLine("</section>");
    }

    // ── AI Section ──────────────────────────────────────────

    private static void AppendAiSection(StringBuilder sb, RiskReport report)
    {
        var ai = report.AiEnrichment!;
        sb.AppendLine("<section class=\"ai-section\">");
        sb.AppendLine("<h2><span class=\"ai-badge\">AI</span> AI Analysis</h2>");

        if (!string.IsNullOrWhiteSpace(ai.Summary))
        {
            sb.AppendLine(CultureInfo.InvariantCulture,
                $"<div class=\"ai-summary\"><p>{Encode(ai.Summary)}</p></div>");
        }

        sb.AppendLine(CultureInfo.InvariantCulture,
            $"<p class=\"meta\">Adapter: {Encode(ai.Provenance.AdapterName)} &middot; Model: {Encode(ai.Provenance.ModelIdentifier)}</p>");
        sb.AppendLine("</section>");
    }

    // ── Scripts ─────────────────────────────────────────────

    private static void AppendScripts(StringBuilder sb, RiskReport report)
    {
        sb.AppendLine("<script src=\"https://cdn.jsdelivr.net/npm/chart.js@4/dist/chart.umd.min.js\"></script>");
        sb.AppendLine("<script>");

        // Dark mode toggle
        sb.AppendLine("""
        (function(){
          var t=document.getElementById('theme-toggle'),b=document.body;
          var stored=localStorage.getItem('d365xray-theme');
          if(stored==='dark')b.classList.add('dark');
          t.addEventListener('click',function(){
            b.classList.toggle('dark');
            localStorage.setItem('d365xray-theme',b.classList.contains('dark')?'dark':'light');
          });
        })();
        """);

        // Findings filter
        sb.AppendLine("""
        (function(){
          var search=document.getElementById('findingSearch');
          var sevFilter=document.getElementById('severityFilter');
          if(!search||!sevFilter)return;
          function applyFilter(){
            var q=search.value.toLowerCase();
            var sev=sevFilter.value;
            document.querySelectorAll('.finding').forEach(function(el){
              var matchText=!q||el.getAttribute('data-text').indexOf(q)!==-1;
              var matchSev=!sev||el.getAttribute('data-severity')===sev;
              el.style.display=matchText&&matchSev?'':'none';
            });
          }
          search.addEventListener('input',applyFilter);
          sevFilter.addEventListener('change',applyFilter);
        })();
        """);

        // Severity chart
        if (report.SeverityCounts.Count > 0)
        {
            var labels = new StringBuilder();
            var data = new StringBuilder();
            var colors = new StringBuilder();
            var first = true;
            foreach (var sev in Enum.GetValues<Severity>().OrderByDescending(s => s))
            {
                if (report.SeverityCounts.TryGetValue(sev, out var count) && count > 0)
                {
                    if (!first) { labels.Append(','); data.Append(','); colors.Append(','); }
                    labels.Append(CultureInfo.InvariantCulture, $"'{sev}'");
                    data.Append(CultureInfo.InvariantCulture, $"{count}");
                    colors.Append(CultureInfo.InvariantCulture, $"'{GetSeverityColor(sev)}'");
                    first = false;
                }
            }

                        var severityChartScript = """
                                (function(){
                                    var ctx=document.getElementById('severityChart');
                                    if(!ctx)return;
                                    new Chart(ctx,{type:'doughnut',data:{labels:[__LABELS__],datasets:[{data:[__DATA__],backgroundColor:[__COLORS__],borderWidth:0}]},options:{responsive:true,plugins:{legend:{position:'right',labels:{color:getComputedStyle(document.body).getPropertyValue('--text').trim()}}}}});
                                })();
                                """;
                        sb.AppendLine(severityChartScript
                                .Replace("__LABELS__", labels.ToString(), StringComparison.Ordinal)
                                .Replace("__DATA__", data.ToString(), StringComparison.Ordinal)
                                .Replace("__COLORS__", colors.ToString(), StringComparison.Ordinal));
        }

        // Category chart
        var catLabels = new StringBuilder();
        var catData = new StringBuilder();
        var catColors = new StringBuilder();
        var categoryCounts = report.Findings
            .GroupBy(f => f.Category)
            .ToDictionary(g => g.Key, g => g.Count());
        var catFirst = true;
        foreach (var cat in Enum.GetValues<FindingCategory>().OrderBy(c => c.ToString(), StringComparer.Ordinal))
        {
            if (categoryCounts.TryGetValue(cat, out var count) && count > 0)
            {
                if (!catFirst) { catLabels.Append(','); catData.Append(','); catColors.Append(','); }
                catLabels.Append(CultureInfo.InvariantCulture, $"'{cat}'");
                catData.Append(CultureInfo.InvariantCulture, $"{count}");
                catColors.Append("'#5b8def'");
                catFirst = false;
            }
        }

        if (!catFirst)
        {
                        var categoryChartScript = """
                                (function(){
                                    var ctx=document.getElementById('categoryChart');
                                    if(!ctx)return;
                                    var textColor=getComputedStyle(document.body).getPropertyValue('--text').trim();
                                    new Chart(ctx,{type:'bar',data:{labels:[__CAT_LABELS__],datasets:[{label:'Findings',data:[__CAT_DATA__],backgroundColor:[__CAT_COLORS__],borderRadius:4}]},options:{responsive:true,indexAxis:'y',plugins:{legend:{display:false}},scales:{x:{ticks:{color:textColor},grid:{color:'rgba(128,128,128,0.15)'}},y:{ticks:{color:textColor},grid:{display:false}}}}});
                                })();
                                """;
                        sb.AppendLine(categoryChartScript
                                .Replace("__CAT_LABELS__", catLabels.ToString(), StringComparison.Ordinal)
                                .Replace("__CAT_DATA__", catData.ToString(), StringComparison.Ordinal)
                                .Replace("__CAT_COLORS__", catColors.ToString(), StringComparison.Ordinal));
        }

        sb.AppendLine("</script>");
    }

    // ── Helpers ──────────────────────────────────────────────

    private static string Encode(string value) => HttpUtility.HtmlEncode(value);

    private static string GetSeverityColor(Severity severity) => severity switch
    {
        Severity.Critical => "#dc3545",
        Severity.High => "#fd7e14",
        Severity.Medium => "#ffc107",
        Severity.Low => "#28a745",
        Severity.Info => "#6c757d",
        _ => "#6c757d"
    };

    private static Dictionary<string, FindingAnnotation> BuildAnnotationLookup(RiskReport report)
    {
        if (report.AiEnrichment is null)
        {
            return [];
        }

        return report.AiEnrichment.FindingAnnotations
            .ToDictionary(kvp => kvp.Key, kvp => kvp.Value, StringComparer.OrdinalIgnoreCase);
    }

    private static void AppendCss(StringBuilder sb)
    {
        sb.AppendLine("""
            :root {
              --bg: #f8f9fa; --card: #fff; --border: #dee2e6; --text: #212529;
              --muted: #6c757d; --gauge-bg: #e9ecef;
              --color-low: #28a745; --color-medium: #ffc107; --color-high: #fd7e14; --color-critical: #dc3545;
            }
            body.dark {
              --bg: #181a1b; --card: #1e2022; --border: #3a3d40; --text: #d1d5db;
              --muted: #9ca3af; --gauge-bg: #2d3033;
            }
            * { box-sizing: border-box; margin: 0; padding: 0; }
            body {
              font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
              background: var(--bg); color: var(--text); padding: 2rem; max-width: 1080px; margin: auto;
              transition: background .2s, color .2s;
            }
            a { color: #4d90fe; }
            body.dark a { color: #7aafff; }
            header { margin-bottom: 1.5rem; background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%); color: #fff; padding: 1.5rem 2rem; border-radius: .75rem; margin: -2rem -2rem 1.5rem; padding-top: 2rem; }
            header a { color: #7aafff; }
            header .meta { color: rgba(255,255,255,.7); }
            .header-row { display: flex; justify-content: space-between; align-items: flex-start; }
            h1 { font-size: 1.8rem; margin-bottom: .25rem; }
            h2 { font-size: 1.3rem; margin: 1.5rem 0 .75rem; }
            h3 { display: inline; font-size: 1.1rem; }
            .meta { color: var(--muted); font-size: .85rem; }
            .theme-btn {
              background: var(--card); border: 1px solid var(--border); border-radius: .5rem;
              color: var(--text); font-size: 1.3rem; cursor: pointer; padding: .35rem .7rem;
              line-height: 1; transition: background .2s;
            }
            .theme-btn:hover { background: var(--border); }
            .mode-badge { display: inline-block; background: #5b8def; color: #fff; padding: .1rem .5rem; border-radius: .2rem; font-size: .75rem; font-weight: 600; letter-spacing: .03em; vertical-align: middle; }

            /* Dashboard */
            .dashboard { display: flex; gap: 1.5rem; align-items: center; flex-wrap: wrap; margin: 1rem 0; }
            .gauge-card { flex: 0 0 160px; }
            .gauge-svg { width: 160px; }
            .gauge-score { font-size: 1.4rem; font-weight: 700; fill: var(--text); }
            .gauge-label { font-size: .55rem; text-transform: uppercase; letter-spacing: .08em; fill: var(--muted); }
            .kpi-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(110px, 1fr)); gap: .75rem; flex: 1; }
            .kpi-card {
              background: var(--card); border: 1px solid var(--border); border-radius: .5rem;
              padding: .75rem 1rem; text-align: center; transition: transform .15s, box-shadow .15s;
              box-shadow: 0 1px 3px rgba(0,0,0,.08);
            }
            .kpi-card:hover { transform: translateY(-2px); box-shadow: 0 4px 12px rgba(0,0,0,.12); }
            .kpi-value { display: block; font-size: 1.8rem; font-weight: 700; }
            .kpi-card.critical .kpi-value { color: var(--color-critical); }
            .kpi-card.high .kpi-value { color: var(--color-high); }
            .kpi-label { font-size: .8rem; color: var(--muted); text-transform: uppercase; letter-spacing: .05em; }

            /* Tables */
            .table-scroll { overflow-x: auto; }
            table { border-collapse: collapse; width: 100%; margin: .5rem 0; }
            th, td { padding: .5rem .75rem; text-align: left; border-bottom: 1px solid var(--border); }
            th { background: var(--card); font-weight: 600; position: sticky; top: 0; }
            .severity-table { max-width: 300px; }

            /* Tags */
            .tag { display: inline-block; padding: .15rem .5rem; border-radius: .25rem;
                   font-size: .8rem; font-weight: 600; color: #fff; }
            .tag.critical { background: #dc3545; }
            .tag.high { background: #fd7e14; }
            .tag.medium { background: #ffc107; color: #212529; }
            .tag.low { background: #28a745; }
            .tag.info { background: #6c757d; }

            /* Charts */
            .chart-container { max-width: 480px; margin: .75rem 0; }

            /* Filter bar */
            .filter-bar { display: flex; gap: .75rem; margin: .75rem 0; flex-wrap: wrap; }
            .filter-input {
              flex: 1; min-width: 200px; padding: .45rem .75rem; border: 1px solid var(--border);
              border-radius: .4rem; background: var(--card); color: var(--text); font-size: .9rem;
              transition: border-color .2s;
            }
            .filter-input:focus { outline: none; border-color: #5b8def; }
            .filter-select {
              padding: .45rem .75rem; border: 1px solid var(--border); border-radius: .4rem;
              background: var(--card); color: var(--text); font-size: .9rem; cursor: pointer;
            }

            /* Findings */
            details { background: var(--card); border: 1px solid var(--border);
                      border-radius: .5rem; margin: .75rem 0; }
            summary { cursor: pointer; padding: .75rem 1rem; }
            summary::-webkit-details-marker { margin-right: .5rem; }
            .finding { padding: .75rem 1rem; border-top: 1px solid var(--border); }
            .finding h4 { font-size: 1rem; margin-bottom: .4rem; }
            .finding p { font-size: .9rem; color: var(--text); margin: .2rem 0; }
            .score-line, .affected, .rule { font-size: .85rem; color: var(--muted); }
            .deep-link { font-size: .85rem; }
            .deep-link a { text-decoration: none; font-weight: 600; }
            .deep-link a:hover { text-decoration: underline; }

            /* Details toggle */
            .details-toggle { background: transparent; border: none; margin: .4rem 0; }
            .details-toggle summary { padding: .3rem 0; font-size: .85rem; color: var(--muted); }
            .details-table { font-size: .85rem; margin: .25rem 0; }
            .details-table td { padding: .25rem .5rem; }
            .detail-key { font-weight: 600; white-space: nowrap; color: var(--muted); }

            /* AI */
            .ai-badge {
              display: inline-block; background: linear-gradient(135deg, #667eea, #764ba2);
              color: #fff; padding: .1rem .45rem; border-radius: .25rem; font-size: .7rem;
              font-weight: 700; letter-spacing: .05em; vertical-align: middle;
            }
            .ai-annotation { background: rgba(102,126,234,.06); border-radius: .4rem; padding: .6rem .8rem; margin: .4rem 0; }
            body.dark .ai-annotation { background: rgba(102,126,234,.12); }
            .ai-commentary { font-size: .88rem; margin: .3rem 0; }
            .ai-actions { margin: .3rem 0 0 1.2rem; font-size: .85rem; }
            .ai-section .ai-summary { background: var(--card); border: 1px solid var(--border); border-radius: .5rem; padding: 1rem; margin: .5rem 0; }

            /* Executive Summary */
            .exec-observations { list-style: none; padding: 0; }
            .exec-observations li { padding: .5rem .75rem; border-left: 3px solid var(--border); margin: .4rem 0; font-size: .92rem; background: var(--card); border-radius: 0 .3rem .3rem 0; }
            .exec-observations li:has(strong) { border-left-color: #5b8def; }

            /* Settings Audit */
            .settings-audit code { background: var(--gauge-bg); padding: .1rem .35rem; border-radius: .2rem; font-size: .85rem; }

            /* Mini KPI rows for sub-sections */
            .mini-kpi-row { display: flex; gap: 1rem; flex-wrap: wrap; margin: .75rem 0 1rem; }
            .mini-kpi { display: inline-flex; align-items: center; gap: .3rem; padding: .4rem .8rem; background: var(--card); border: 1px solid var(--border); border-radius: .4rem; font-size: .85rem; }
            .mini-kpi strong { font-size: 1.1rem; }
            .mini-kpi.warn { border-color: #f59e0b; background: rgba(245,158,11,.08); }
            .mini-kpi.warn strong { color: #f59e0b; }

            /* Entity governance / env variables */
            .entity-governance code, .env-variables code { background: var(--gauge-bg); padding: .1rem .35rem; border-radius: .2rem; font-size: .85rem; }

            /* Footer */
            footer { margin-top: 3rem; text-align: center; color: var(--muted); font-size: .8rem; }
            """);
    }
}
