using System.Globalization;
using System.Text;
using System.Web;
using D365Xray.Core.Model;

namespace D365Xray.Reporting;

/// <summary>
/// Exports a <see cref="RiskReport"/> as a self-contained HTML document
/// with inline CSS, Chart.js charts, dark mode toggle, deep links,
/// environment inventory, and collapsible finding groups.
/// Produces <c>report.html</c> in the output directory.
/// </summary>
internal sealed class HtmlReportExporter
{
    public async Task ExportAsync(
        RiskReport report,
        string outputDirectory,
        CancellationToken cancellationToken = default)
    {
        Directory.CreateDirectory(outputDirectory);
        var path = Path.Combine(outputDirectory, "report.html");
        var html = Build(report);
        await File.WriteAllTextAsync(path, html, Encoding.UTF8, cancellationToken);
    }

    internal static string Build(RiskReport report)
    {
        var sb = new StringBuilder(16_384);
        sb.AppendLine("<!DOCTYPE html>");
        sb.AppendLine("<html lang=\"en\">");
        sb.AppendLine("<head>");
        sb.AppendLine("<meta charset=\"utf-8\">");
        sb.AppendLine("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
        sb.AppendLine("<title>D365 X-Ray Risk Report</title>");
        sb.AppendLine("<style>");
        AppendCss(sb);
        sb.AppendLine("</style>");
        sb.AppendLine("</head>");
        sb.AppendLine("<body>");

        // Header with dark mode toggle
        sb.AppendLine("<header>");
        sb.AppendLine("<div class=\"header-row\">");
        sb.AppendLine("<div>");
        sb.AppendLine("<h1>D365 X-Ray Risk Report</h1>");
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"<p class=\"meta\">Captured {Encode(report.Metadata.CapturedAtUtc.ToString("u"))} &middot; Tool v{Encode(report.Metadata.ToolVersion)}</p>");
        sb.AppendLine("</div>");
        sb.AppendLine("<button id=\"theme-toggle\" class=\"theme-btn\" title=\"Toggle dark mode\" aria-label=\"Toggle dark mode\">&#9790;</button>");
        sb.AppendLine("</div>");
        sb.AppendLine("</header>");
        sb.AppendLine("<main>");

        // Dashboard row: SVG gauge + KPI cards
        AppendDashboard(sb, report);

        // Environment inventory
        if (report.EnvironmentSummaries.Count > 0)
        {
            AppendEnvironmentInventory(sb, report);
        }
        else
        {
            AppendEnvironmentsList(sb, report);
        }

        // Severity breakdown as bar chart
        AppendSeveritySection(sb, report);

        // Analysis coverage
        AppendAnalysisCoverage(sb, report);

        // Findings
        AppendFindings(sb, report);

        // AI Enrichment
        if (report.AiEnrichment is not null)
        {
            AppendAiSection(sb, report);
        }

        sb.AppendLine("</main>");
        sb.AppendLine("<footer><p>Generated by <strong>d365-xray</strong></p></footer>");

        // Chart.js + inline script
        AppendScripts(sb, report);

        sb.AppendLine("</body>");
        sb.AppendLine("</html>");

        return sb.ToString();
    }

    // ── Dashboard ───────────────────────────────────────────

    private static void AppendDashboard(StringBuilder sb, RiskReport report)
    {
        var score = report.OverallRiskScore;
        var level = report.OverallRiskLevel;
        var levelClass = level.ToString().ToLowerInvariant();
        var angle = score / 100.0 * 180.0;
        // SVG arc for gauge (half circle)
        var rad = angle * Math.PI / 180.0;
        var x = 60 + 50 * Math.Cos(Math.PI - rad);
        var y = 65 - 50 * Math.Sin(Math.PI - rad);
        var largeArc = angle > 90 ? 1 : 0;

        sb.AppendLine("<section class=\"dashboard\">");

        // SVG Gauge
        sb.AppendLine("<div class=\"gauge-card\">");
        sb.AppendLine("<svg viewBox=\"0 0 120 75\" class=\"gauge-svg\">");
        sb.AppendLine("  <path d=\"M 10 65 A 50 50 0 0 1 110 65\" fill=\"none\" stroke=\"var(--gauge-bg)\" stroke-width=\"8\" stroke-linecap=\"round\"/>");
        if (score > 0)
        {
            sb.AppendLine(CultureInfo.InvariantCulture,
                $"  <path d=\"M 10 65 A 50 50 0 {largeArc} 1 {x:F1} {y:F1}\" fill=\"none\" stroke=\"var(--color-{levelClass})\" stroke-width=\"8\" stroke-linecap=\"round\"/>");
        }
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"  <text x=\"60\" y=\"58\" text-anchor=\"middle\" class=\"gauge-score\">{score}</text>");
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"  <text x=\"60\" y=\"72\" text-anchor=\"middle\" class=\"gauge-label\">{level}</text>");
        sb.AppendLine("</svg>");
        sb.AppendLine("</div>");

        // KPI cards
        sb.AppendLine("<div class=\"kpi-grid\">");
        AppendKpiCard(sb, "Findings", report.Findings.Count.ToString(CultureInfo.InvariantCulture), "total");
        var critical = report.SeverityCounts.GetValueOrDefault(Severity.Critical);
        var high = report.SeverityCounts.GetValueOrDefault(Severity.High);
        AppendKpiCard(sb, "Critical", critical.ToString(CultureInfo.InvariantCulture), "critical");
        AppendKpiCard(sb, "High", high.ToString(CultureInfo.InvariantCulture), "high");
        AppendKpiCard(sb, "Environments", report.ComparedEnvironments.Count.ToString(CultureInfo.InvariantCulture), "total");
        sb.AppendLine("</div>");

        sb.AppendLine("</section>");
    }

    private static void AppendKpiCard(StringBuilder sb, string label, string value, string cssClass)
    {
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"<div class=\"kpi-card {cssClass}\"><span class=\"kpi-value\">{value}</span><span class=\"kpi-label\">{Encode(label)}</span></div>");
    }

    // ── Environment Inventory ───────────────────────────────

    private static void AppendEnvironmentInventory(StringBuilder sb, RiskReport report)
    {
        sb.AppendLine("<section class=\"env-inventory\">");
        sb.AppendLine("<h2>Environment Inventory</h2>");
        sb.AppendLine("<div class=\"table-scroll\">");
        sb.AppendLine("<table><thead><tr>");
        sb.AppendLine("<th>Environment</th><th>Type</th><th>Solutions</th><th>Components</th><th>Workflows</th><th>Plugins</th><th>SDK Steps</th><th>Web Resources</th><th>Conn. Refs</th><th>Env Vars</th><th>Business Rules</th><th>Connectors</th><th>Endpoints</th>");
        sb.AppendLine("</tr></thead><tbody>");

        foreach (var env in report.EnvironmentSummaries)
        {
            sb.Append(CultureInfo.InvariantCulture,
                $"<tr><td><a href=\"{Encode(env.EnvironmentUrl.ToString())}\" target=\"_blank\" rel=\"noopener\">{Encode(env.EnvironmentDisplayName)}</a></td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{Encode(env.EnvironmentType.ToString())}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{env.Solutions}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{env.Components}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{env.Workflows}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{env.PluginAssemblies}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{env.SdkSteps}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{env.WebResources}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{env.ConnectionReferences}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{env.EnvironmentVariables}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{env.BusinessRules}</td>");
            sb.Append(CultureInfo.InvariantCulture, $"<td>{env.CustomConnectors}</td>");
            sb.AppendLine(CultureInfo.InvariantCulture, $"<td>{env.ServiceEndpoints}</td></tr>");
        }

        sb.AppendLine("</tbody></table>");
        sb.AppendLine("</div>");
        sb.AppendLine("</section>");
    }

    private static void AppendEnvironmentsList(StringBuilder sb, RiskReport report)
    {
        sb.AppendLine("<section class=\"environments\">");
        sb.AppendLine("<h2>Compared Environments</h2>");
        sb.AppendLine("<ul>");
        foreach (var env in report.ComparedEnvironments)
        {
            sb.AppendLine(CultureInfo.InvariantCulture,
                $"<li><strong>{Encode(env.DisplayName)}</strong> &mdash; <a href=\"{Encode(env.EnvironmentUrl.ToString())}\" target=\"_blank\" rel=\"noopener\"><code>{Encode(env.EnvironmentUrl.ToString())}</code></a></li>");
        }
        sb.AppendLine("</ul>");
        sb.AppendLine("</section>");
    }

    // ── Severity Section ────────────────────────────────────

    private static void AppendSeveritySection(StringBuilder sb, RiskReport report)
    {
        if (report.SeverityCounts.Count == 0)
        {
            return;
        }

        sb.AppendLine("<section class=\"severity-summary\">");
        sb.AppendLine("<h2>Severity Breakdown</h2>");
        sb.AppendLine("<div class=\"chart-container\"><canvas id=\"severityChart\"></canvas></div>");

        // Fallback table (also useful for no-JS)
        sb.AppendLine("<table class=\"severity-table\"><thead><tr><th>Severity</th><th>Count</th></tr></thead><tbody>");
        foreach (var severity in Enum.GetValues<Severity>().OrderByDescending(s => s))
        {
            if (report.SeverityCounts.TryGetValue(severity, out var count) && count > 0)
            {
                var sevClass = severity.ToString().ToLowerInvariant();
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"<tr><td><span class=\"tag {sevClass}\">{severity}</span></td><td>{count}</td></tr>");
            }
        }
        sb.AppendLine("</tbody></table>");
        sb.AppendLine("</section>");
    }

    // ── Analysis Coverage ───────────────────────────────────

    private static void AppendAnalysisCoverage(StringBuilder sb, RiskReport report)
    {
        var categoryCounts = report.Findings
            .GroupBy(f => f.Category)
            .ToDictionary(g => g.Key, g => g.Count());
        var envCount = report.ComparedEnvironments.Count;
        var hasProdLike = report.ComparedEnvironments.Any(e =>
            e.EnvironmentType is EnvironmentType.Prod or EnvironmentType.Staging);

        sb.AppendLine("<section class=\"analysis-coverage\">");
        sb.AppendLine("<h2>Analysis Coverage</h2>");

        // Chart
        sb.AppendLine("<div class=\"chart-container\"><canvas id=\"categoryChart\"></canvas></div>");

        sb.AppendLine("<div class=\"table-scroll\">");
        sb.AppendLine("<table><thead><tr><th>Category</th><th>Scope</th><th>Applicable</th><th>Findings</th></tr></thead><tbody>");
        foreach (var category in Enum.GetValues<FindingCategory>().OrderBy(c => c.ToString(), StringComparer.Ordinal))
        {
            categoryCounts.TryGetValue(category, out var count);
            var scope = CategoryHelper.GetCategoryScope(category);
            var applicable = CategoryHelper.IsCategoryApplicable(category, envCount, hasProdLike) ? "yes" : "no";
            sb.AppendLine(CultureInfo.InvariantCulture,
                $"<tr><td>{Encode(category.ToString())}</td><td>{Encode(scope)}</td><td>{applicable}</td><td>{count}</td></tr>");
        }
        sb.AppendLine("</tbody></table>");
        sb.AppendLine("</div>");
        sb.AppendLine("<p class=\"meta\">Applicable=no means the check is out of scope for the current run shape.</p>");
        sb.AppendLine("</section>");
    }

    // ── Findings ────────────────────────────────────────────

    private static void AppendFindings(StringBuilder sb, RiskReport report)
    {
        if (report.Findings.Count == 0)
        {
            return;
        }

        sb.AppendLine("<section class=\"findings\">");
        sb.AppendLine("<h2>Findings</h2>");

        // Build annotation lookup for AI enrichment
        var annotations = BuildAnnotationLookup(report);

        var grouped = report.Findings
            .GroupBy(f => f.Category)
            .OrderByDescending(g => g.Max(f => f.RiskScore ?? 0));

        foreach (var group in grouped)
        {
            sb.AppendLine("<details open>");
            sb.AppendLine(CultureInfo.InvariantCulture,
                $"<summary><h3>{Encode(group.Key.ToString())} ({group.Count()})</h3></summary>");

            foreach (var finding in group.OrderByDescending(f => f.Severity))
            {
                var sevClass = finding.Severity.ToString().ToLowerInvariant();
                sb.AppendLine("<div class=\"finding\">");
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"  <h4><span class=\"tag {sevClass}\">{finding.Severity}</span> {Encode(finding.Title)}</h4>");
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"  <p>{Encode(finding.Description)}</p>");

                if (finding.RiskScore.HasValue)
                {
                    sb.AppendLine(CultureInfo.InvariantCulture,
                        $"  <p class=\"score-line\">Risk Score: <strong>{finding.RiskScore}</strong></p>");
                }

                if (finding.AffectedEnvironments.Count > 0)
                {
                    sb.AppendLine(CultureInfo.InvariantCulture,
                        $"  <p class=\"affected\">Affected: {Encode(string.Join(", ", finding.AffectedEnvironments))}</p>");
                }

                if (finding.RuleId is not null)
                {
                    sb.AppendLine(CultureInfo.InvariantCulture,
                        $"  <p class=\"rule\">Rule: <code>{Encode(finding.RuleId)}</code></p>");
                }

                // Deep link
                var deepLink = DeepLinkBuilder.TryBuildLink(finding.Details);
                if (deepLink is not null)
                {
                    sb.AppendLine(CultureInfo.InvariantCulture,
                        $"  <p class=\"deep-link\"><a href=\"{Encode(deepLink)}\" target=\"_blank\" rel=\"noopener\">Open in Dynamics 365 &#8599;</a></p>");
                }

                // Details table
                if (finding.Details.Count > 0)
                {
                    sb.AppendLine("  <details class=\"details-toggle\">");
                    sb.AppendLine("  <summary>Details</summary>");
                    sb.AppendLine("  <table class=\"details-table\"><tbody>");
                    foreach (var (key, value) in finding.Details)
                    {
                        sb.AppendLine(CultureInfo.InvariantCulture,
                            $"    <tr><td class=\"detail-key\">{Encode(key)}</td><td>{Encode(value)}</td></tr>");
                    }
                    sb.AppendLine("  </tbody></table>");
                    sb.AppendLine("  </details>");
                }

                // AI annotation for this finding
                if (annotations.TryGetValue(finding.FindingId, out var annotation))
                {
                    sb.AppendLine("  <div class=\"ai-annotation\">");
                    sb.AppendLine("    <span class=\"ai-badge\">AI</span>");
                    if (!string.IsNullOrWhiteSpace(annotation.Commentary))
                    {
                        sb.AppendLine(CultureInfo.InvariantCulture,
                            $"    <p class=\"ai-commentary\">{Encode(annotation.Commentary)}</p>");
                    }
                    if (annotation.SuggestedActions.Count > 0)
                    {
                        sb.AppendLine("    <ul class=\"ai-actions\">");
                        foreach (var action in annotation.SuggestedActions)
                        {
                            sb.AppendLine(CultureInfo.InvariantCulture,
                                $"      <li>{Encode(action)}</li>");
                        }
                        sb.AppendLine("    </ul>");
                    }
                    sb.AppendLine("  </div>");
                }

                sb.AppendLine("</div>");
            }

            sb.AppendLine("</details>");
        }

        sb.AppendLine("</section>");
    }

    // ── AI Section ──────────────────────────────────────────

    private static void AppendAiSection(StringBuilder sb, RiskReport report)
    {
        var ai = report.AiEnrichment!;
        sb.AppendLine("<section class=\"ai-section\">");
        sb.AppendLine("<h2><span class=\"ai-badge\">AI</span> AI Analysis</h2>");

        if (!string.IsNullOrWhiteSpace(ai.Summary))
        {
            sb.AppendLine(CultureInfo.InvariantCulture,
                $"<div class=\"ai-summary\"><p>{Encode(ai.Summary)}</p></div>");
        }

        sb.AppendLine(CultureInfo.InvariantCulture,
            $"<p class=\"meta\">Adapter: {Encode(ai.Provenance.AdapterName)} &middot; Model: {Encode(ai.Provenance.ModelIdentifier)}</p>");
        sb.AppendLine("</section>");
    }

    // ── Scripts ─────────────────────────────────────────────

    private static void AppendScripts(StringBuilder sb, RiskReport report)
    {
        sb.AppendLine("<script src=\"https://cdn.jsdelivr.net/npm/chart.js@4/dist/chart.umd.min.js\"></script>");
        sb.AppendLine("<script>");

        // Dark mode toggle
        sb.AppendLine("""
        (function(){
          var t=document.getElementById('theme-toggle'),b=document.body;
          var stored=localStorage.getItem('d365xray-theme');
          if(stored==='dark')b.classList.add('dark');
          t.addEventListener('click',function(){
            b.classList.toggle('dark');
            localStorage.setItem('d365xray-theme',b.classList.contains('dark')?'dark':'light');
          });
        })();
        """);

        // Severity chart
        if (report.SeverityCounts.Count > 0)
        {
            var labels = new StringBuilder();
            var data = new StringBuilder();
            var colors = new StringBuilder();
            var first = true;
            foreach (var sev in Enum.GetValues<Severity>().OrderByDescending(s => s))
            {
                if (report.SeverityCounts.TryGetValue(sev, out var count) && count > 0)
                {
                    if (!first) { labels.Append(','); data.Append(','); colors.Append(','); }
                    labels.Append(CultureInfo.InvariantCulture, $"'{sev}'");
                    data.Append(CultureInfo.InvariantCulture, $"{count}");
                    colors.Append(CultureInfo.InvariantCulture, $"'{GetSeverityColor(sev)}'");
                    first = false;
                }
            }

                        var severityChartScript = """
                                (function(){
                                    var ctx=document.getElementById('severityChart');
                                    if(!ctx)return;
                                    new Chart(ctx,{type:'doughnut',data:{labels:[__LABELS__],datasets:[{data:[__DATA__],backgroundColor:[__COLORS__],borderWidth:0}]},options:{responsive:true,plugins:{legend:{position:'right',labels:{color:getComputedStyle(document.body).getPropertyValue('--text').trim()}}}}});
                                })();
                                """;
                        sb.AppendLine(severityChartScript
                                .Replace("__LABELS__", labels.ToString(), StringComparison.Ordinal)
                                .Replace("__DATA__", data.ToString(), StringComparison.Ordinal)
                                .Replace("__COLORS__", colors.ToString(), StringComparison.Ordinal));
        }

        // Category chart
        var catLabels = new StringBuilder();
        var catData = new StringBuilder();
        var catColors = new StringBuilder();
        var categoryCounts = report.Findings
            .GroupBy(f => f.Category)
            .ToDictionary(g => g.Key, g => g.Count());
        var catFirst = true;
        foreach (var cat in Enum.GetValues<FindingCategory>().OrderBy(c => c.ToString(), StringComparer.Ordinal))
        {
            if (categoryCounts.TryGetValue(cat, out var count) && count > 0)
            {
                if (!catFirst) { catLabels.Append(','); catData.Append(','); catColors.Append(','); }
                catLabels.Append(CultureInfo.InvariantCulture, $"'{cat}'");
                catData.Append(CultureInfo.InvariantCulture, $"{count}");
                catColors.Append("'#5b8def'");
                catFirst = false;
            }
        }

        if (!catFirst)
        {
                        var categoryChartScript = """
                                (function(){
                                    var ctx=document.getElementById('categoryChart');
                                    if(!ctx)return;
                                    var textColor=getComputedStyle(document.body).getPropertyValue('--text').trim();
                                    new Chart(ctx,{type:'bar',data:{labels:[__CAT_LABELS__],datasets:[{label:'Findings',data:[__CAT_DATA__],backgroundColor:[__CAT_COLORS__],borderRadius:4}]},options:{responsive:true,indexAxis:'y',plugins:{legend:{display:false}},scales:{x:{ticks:{color:textColor},grid:{color:'rgba(128,128,128,0.15)'}},y:{ticks:{color:textColor},grid:{display:false}}}}});
                                })();
                                """;
                        sb.AppendLine(categoryChartScript
                                .Replace("__CAT_LABELS__", catLabels.ToString(), StringComparison.Ordinal)
                                .Replace("__CAT_DATA__", catData.ToString(), StringComparison.Ordinal)
                                .Replace("__CAT_COLORS__", catColors.ToString(), StringComparison.Ordinal));
        }

        sb.AppendLine("</script>");
    }

    // ── Helpers ──────────────────────────────────────────────

    private static string Encode(string value) => HttpUtility.HtmlEncode(value);

    private static string GetSeverityColor(Severity severity) => severity switch
    {
        Severity.Critical => "#dc3545",
        Severity.High => "#fd7e14",
        Severity.Medium => "#ffc107",
        Severity.Low => "#28a745",
        Severity.Info => "#6c757d",
        _ => "#6c757d"
    };

    private static Dictionary<string, FindingAnnotation> BuildAnnotationLookup(RiskReport report)
    {
        if (report.AiEnrichment is null)
        {
            return [];
        }

        return report.AiEnrichment.FindingAnnotations
            .ToDictionary(kvp => kvp.Key, kvp => kvp.Value, StringComparer.OrdinalIgnoreCase);
    }

    private static void AppendCss(StringBuilder sb)
    {
        sb.AppendLine("""
            :root {
              --bg: #f8f9fa; --card: #fff; --border: #dee2e6; --text: #212529;
              --muted: #6c757d; --gauge-bg: #e9ecef;
              --color-low: #28a745; --color-medium: #ffc107; --color-high: #fd7e14; --color-critical: #dc3545;
            }
            body.dark {
              --bg: #181a1b; --card: #1e2022; --border: #3a3d40; --text: #d1d5db;
              --muted: #9ca3af; --gauge-bg: #2d3033;
            }
            * { box-sizing: border-box; margin: 0; padding: 0; }
            body {
              font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
              background: var(--bg); color: var(--text); padding: 2rem; max-width: 1080px; margin: auto;
              transition: background .2s, color .2s;
            }
            a { color: #4d90fe; }
            body.dark a { color: #7aafff; }
            header { margin-bottom: 1.5rem; }
            .header-row { display: flex; justify-content: space-between; align-items: flex-start; }
            h1 { font-size: 1.8rem; margin-bottom: .25rem; }
            h2 { font-size: 1.3rem; margin: 1.5rem 0 .75rem; }
            h3 { display: inline; font-size: 1.1rem; }
            .meta { color: var(--muted); font-size: .85rem; }
            .theme-btn {
              background: var(--card); border: 1px solid var(--border); border-radius: .5rem;
              color: var(--text); font-size: 1.3rem; cursor: pointer; padding: .35rem .7rem;
              line-height: 1; transition: background .2s;
            }
            .theme-btn:hover { background: var(--border); }

            /* Dashboard */
            .dashboard { display: flex; gap: 1.5rem; align-items: center; flex-wrap: wrap; margin: 1rem 0; }
            .gauge-card { flex: 0 0 160px; }
            .gauge-svg { width: 160px; }
            .gauge-score { font-size: 1.4rem; font-weight: 700; fill: var(--text); }
            .gauge-label { font-size: .55rem; text-transform: uppercase; letter-spacing: .08em; fill: var(--muted); }
            .kpi-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(110px, 1fr)); gap: .75rem; flex: 1; }
            .kpi-card {
              background: var(--card); border: 1px solid var(--border); border-radius: .5rem;
              padding: .75rem 1rem; text-align: center; transition: transform .15s;
            }
            .kpi-card:hover { transform: translateY(-2px); }
            .kpi-value { display: block; font-size: 1.8rem; font-weight: 700; }
            .kpi-card.critical .kpi-value { color: var(--color-critical); }
            .kpi-card.high .kpi-value { color: var(--color-high); }
            .kpi-label { font-size: .8rem; color: var(--muted); text-transform: uppercase; letter-spacing: .05em; }

            /* Tables */
            .table-scroll { overflow-x: auto; }
            table { border-collapse: collapse; width: 100%; margin: .5rem 0; }
            th, td { padding: .5rem .75rem; text-align: left; border-bottom: 1px solid var(--border); }
            th { background: var(--card); font-weight: 600; position: sticky; top: 0; }
            .severity-table { max-width: 300px; }

            /* Tags */
            .tag { display: inline-block; padding: .15rem .5rem; border-radius: .25rem;
                   font-size: .8rem; font-weight: 600; color: #fff; }
            .tag.critical { background: #dc3545; }
            .tag.high { background: #fd7e14; }
            .tag.medium { background: #ffc107; color: #212529; }
            .tag.low { background: #28a745; }
            .tag.info { background: #6c757d; }

            /* Charts */
            .chart-container { max-width: 480px; margin: .75rem 0; }

            /* Findings */
            details { background: var(--card); border: 1px solid var(--border);
                      border-radius: .5rem; margin: .75rem 0; }
            summary { cursor: pointer; padding: .75rem 1rem; }
            summary::-webkit-details-marker { margin-right: .5rem; }
            .finding { padding: .75rem 1rem; border-top: 1px solid var(--border); }
            .finding h4 { font-size: 1rem; margin-bottom: .4rem; }
            .finding p { font-size: .9rem; color: var(--text); margin: .2rem 0; }
            .score-line, .affected, .rule { font-size: .85rem; color: var(--muted); }
            .deep-link { font-size: .85rem; }
            .deep-link a { text-decoration: none; font-weight: 600; }
            .deep-link a:hover { text-decoration: underline; }

            /* Details toggle */
            .details-toggle { background: transparent; border: none; margin: .4rem 0; }
            .details-toggle summary { padding: .3rem 0; font-size: .85rem; color: var(--muted); }
            .details-table { font-size: .85rem; margin: .25rem 0; }
            .details-table td { padding: .25rem .5rem; }
            .detail-key { font-weight: 600; white-space: nowrap; color: var(--muted); }

            /* AI */
            .ai-badge {
              display: inline-block; background: linear-gradient(135deg, #667eea, #764ba2);
              color: #fff; padding: .1rem .45rem; border-radius: .25rem; font-size: .7rem;
              font-weight: 700; letter-spacing: .05em; vertical-align: middle;
            }
            .ai-annotation { background: rgba(102,126,234,.06); border-radius: .4rem; padding: .6rem .8rem; margin: .4rem 0; }
            body.dark .ai-annotation { background: rgba(102,126,234,.12); }
            .ai-commentary { font-size: .88rem; margin: .3rem 0; }
            .ai-actions { margin: .3rem 0 0 1.2rem; font-size: .85rem; }
            .ai-section .ai-summary { background: var(--card); border: 1px solid var(--border); border-radius: .5rem; padding: 1rem; margin: .5rem 0; }

            /* Footer */
            footer { margin-top: 3rem; text-align: center; color: var(--muted); font-size: .8rem; }
            """);
    }
}
