namespace D365Xray.Core.Model;

/// <summary>
/// Options controlling the optional AI enrichment pass.
/// </summary>
public sealed record AiAnalysisOptions
{
    /// <summary>
    /// User-supplied Markdown with domain-specific instructions for the LLM.
    /// </summary>
    public required string CustomInstructionsMarkdown { get; init; }

    /// <summary>
    /// Model identifier passed to the adapter (e.g. "gpt-4o", "claude-3.5-sonnet").
    /// Interpretation is adapter-specific.
    /// </summary>
    public string? ModelIdentifier { get; init; }

    /// <summary>
    /// Optional upper-bound on output tokens. Null = adapter default.
    /// </summary>
    public int? MaxTokenBudget { get; init; }
}

/// <summary>
/// Result of an optional AI enrichment pass over the risk report.
/// Every field carries explicit provenance so AI content is never silent.
/// </summary>
public sealed record AiEnrichmentResult
{
    /// <summary>
    /// AI-generated executive summary of the risk report.
    /// </summary>
    public string? Summary { get; init; }

    /// <summary>
    /// Per-finding AI commentary, keyed by <see cref="Finding.FindingId"/>.
    /// </summary>
    public IReadOnlyDictionary<string, FindingAnnotation> FindingAnnotations { get; init; } =
        new Dictionary<string, FindingAnnotation>();

    /// <summary>
    /// Explicit provenance metadata — must always be populated when AI was invoked.
    /// </summary>
    public required AiProvenance Provenance { get; init; }
}

/// <summary>
/// AI commentary attached to a specific finding.
/// </summary>
public sealed record FindingAnnotation
{
    /// <summary>
    /// AI-generated explanation or recommendation for this finding.
    /// </summary>
    public required string Commentary { get; init; }

    /// <summary>
    /// Suggested remediation steps (may be empty).
    /// </summary>
    public IReadOnlyList<string> SuggestedActions { get; init; } = [];
}

/// <summary>
/// Explicit provenance marker stamped on every AI-generated output.
/// Ensures AI content is never mixed silently into deterministic results.
/// </summary>
public sealed record AiProvenance
{
    public required DateTimeOffset GeneratedAtUtc { get; init; }
    public required string ModelIdentifier { get; init; }
    public required string AdapterName { get; init; }

    /// <summary>
    /// Fixed disclaimer included in every AI output section.
    /// </summary>
    public string Disclaimer { get; init; } =
        "This content was generated by an AI model and may contain inaccuracies. " +
        "Review all recommendations before acting on them.";
}
